export const strings = {
  appName: 'Pacer Time',
  pages: {
    home: 'Inicio',
    signUp: 'Crear cuenta',
    signIn: 'Iniciar sesión',
    createUsers: 'Crear usuarios',
    uploadRunners: 'Cargar competidores',
    menu: 'Menú',
    account: {
      title: 'Mi perfil',
      conf: 'Configuración',
      logOut: 'Cerrar sesión',
    },
  },
  auth: {
    signUp: {
      title: 'Crear cuenta',
      instructions: 'Ingresa tus datos para crear una cuenta',
      name: 'El nombre debe tener al menos 1 carácter',
      lastName: 'El apellido debe tener al menos 1 carácter',
      phoneNumber: 'El número de teléfono debe tener el formato 229-100-1234',
      email: 'Email inválido',
      password: 'Contraseña inválida',
      passwordDontMatch: 'Las contraseñas no coinciden',
      error: 'Ha ocurrido un error inesperado al crear la cuenta.',
      existingEmail: 'Ya existe una cuenta con este correo electrónico.',
      haveAnAccount: '¿Ya tienes cuenta?',
      loading: 'Creando cuenta...',
      success: '¡Cuenta creada exitosamente!',
    },
    signIn: {
      title: 'Iniciar sesión',
      loading: 'Iniciando sesión...',
      success: '¡Inicio de sesión exitoso!',
      error: 'Email o contraseña incorrectos',
      instructions: 'Ingresa tu email y contraseña para iniciar sesión'
    },
    fields: {
      name: 'Nombre',
      surnames: 'Apellidos',
      fatherLastName: 'Apellido paterno',
      motherLastName: 'Apellido materno',
      eventName: 'Evento / Organizador',
      city: 'Ciudad',
      state: 'Estado',
      country: 'País',
      email: 'Correo electrónico',
      password: 'Contraseña',
      confirmPassword: 'Confirmar contraseña',
      phoneNumber: 'Número de teléfono',
      passwordRequirements: 'La contraseña debe tener al menos 8 caracteres.',
      forgotPassword: '¿Olvidaste tu contraseña?',
      noAccount: '¿No tienes cuenta?',
      checkFields: 'Por favor verifica los campos del formulario.',
    },
  },
  events: {
    name: 'Nombre del evento',
    startsAt: 'Fecha de inicio',
    endsAt: 'Fecha de fin',
    edition: 'Edición',
    logo: 'Seleccione el archivo para el logo del evento',
    banner: 'Seleccione el archivo para el banner del evento',
    requiresShirtSize: '¿Requiere talla de playeras?',
    customsQuestions: 'Preguntas personalizadas',
    waiver: 'Seleccione el documento de exoneración',
    webSite: 'Url de su sitio web',
    nameRequired: 'El nombre del evento es obligatorio',
    startsAtRequired: 'La fecha de inicio es obligatoria',
    endsAtRequired: 'La fecha de fin es obligatoria',
  },
  actions: {
    edit: 'Editar',
    delete: 'Eliminar',
    copyName: 'Copiar nombre',
    search: 'Buscar',
  }
}