import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";
import {auth} from "@/lib/auth";
import {NavBar} from "@/components/ui/navBar";
import {SessionProvider} from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  console.log('session::', session);

  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {/*<SessionProvider session={session}>*/}
        <NavBar session={session} />
        {/*<NavBar />*/}
        <main className="min-h-screen">
          {children}
        </main>
        <Toaster position={"top-center"}/>
      {/*</SessionProvider>*/}
      </body>
    </html>
  );
}
